os:
  - linux
services:
  - docker
language: java
node_js:
  - "6.9.1"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.gradle
env:
  - NODE_VERSION=6.9.1
before_install:
  - nvm install $NODE_VERSION
  - npm install -g npm
  - npm install -g bower gulp-cli
  - node -v
  - npm -v
  - bower -v
  - gulp -v
  - java -version
install: npm install
script:
  - ./gradlew clean
  - ./gradlew test
  - sonar-scanner
  - gulp test
  - ./gradlew bootRepackage -Pprod -x test
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
  slack:
    secure: C5BueFTK3x4eP5yf0pxo5WyG2syWW+LUcfUw40myzszy2oNLY0SGKSx9K5j/kn3kJLLXaoP9rwjB5VhrHuk2QV5rW9inrTzcL5tdpH8lvL6vloPJ5g0q5GfleVEpiYHCVQ1ZQ+5bmHnkPHUTDR+csEB6a1W6Tk0/iCZuScLFZyjUhfyOutR+gz4Ur3aYCl7u53NHJ5uVTWW3fZD/Ma5x76tOke8hl34Y60ss01Db8dq0Jp7XyS+qoZzXPzOqxH+2mD0AUJUuvxqJuyYRcKnnAYkWsvh4+Li8bY0K10sp95MscjAhlHyOfyP6SLGwhmgoFfbnMLOcPw+S80kI3cv/z542VcJwivPRdbPXJN6cPbVWhg7rlv6IqzUT8jAHfxPZcnLNP9ce/8847gPbf1uHUasWUFll9XNd+r2/KM4oHBf6cFNz+e2WPpzUeEZEj85+HLKtqRkbjDkk3BjtTY/akvcMY/56A0jTvjNx1oPCHuZ0btMC6xHRw8SYm0S5Ghq+9YIWpr1vBTmnMraGI8fFh9oop9Q9VS9pqxHXfbJZybePHOaE6+ItIDzjLCXQk44XvykipxZVQ5WetZHmbf0c0DBGzXfBRnpCI2KId+aQJ3ftC5OMAW782GwHaPtp5YL2PaoYCtvN0UWC3CsDvlYJGkqsdCC7v31/IQUlo+DkkEM=

addons:
  sonarqube:
    token:
      secure: I4cTnHv7c3MoBeK6Z46nShEA4tXCf7rF326E/4yz7NQLnYtugj64utbohkllG2Xuqo8sV4xzIpwJhv9WHO2pdu6v8VXWcQhkoqp3Ltu27xYm9ZfGw0wY/wMEhO3Xuk3atnUK2G0RfNCZChN7Nuj9CRTgwXE8a6kd2FZfabQjLKzT8fqjUg+eoVB6tLsw5q4/CHN65ynHaUFXhHzDI00tchFSEffkDX/se4wGpAyoV20HvdjjARemy+LO7o5msAoxMTN71ZuCmK4tfFsBtgGv+nMlpXdO0HfQA4n2OWuklRcm9IgX6GzZ7NPVez8MyDNaDGoiyz90gfWobvl41ylzzkOvCLikfTlK+Qjw8wZuJUNRsjlnC5Xvei1ju2CKTYzpmK7ZPrVF8rwN0tfCDZgRVzn3UF9eL7Dvx3v1WZK46RMc8nVevRDlx7OwzCqD5r+ATegB38U1zg8HEKIJBS547rTiZFLHZrXQJvrg2vYBHbqpv7AEouKA6b1P6qgOXYFZa0P86DTsNDT+G0MMbCZ4s/pdFuetnuaWskhNU5lfb4Jr1chObYU7Xo604UnfCFK+wtO6+IfVUIGisySr9GYFQoGrpjXtapJ/syZ2UH544uP69/73+qBaAF9CuRyvlniwXhdpnghrjNK4zkSAMwAeDL3QsiB2W/RYTiT9hLaK5BI=
